[package]
name = "vgtk"
version = "0.1.0"
authors = ["Bodil Stokke <bodil@bodil.org>"]

[dependencies]
gio = "0.5.0"
glib = "0.6.0"
glib-sys = "0.7.0"
gtk-sys = "0.7.0"
gobject-sys = "0.7.0"

[dependencies.gtk]
version = "0.5.0"
features = ["v3_22", "embed-lgpl-docs"]
