[package]
name = "vgtk"
version = "0.1.0"
authors = ["Bodil Stokke <bodil@bodil.org>"]
edition = "2018"
license = "LGPL-3.0+"

[dependencies]
gio = "0.7.0"
glib = "0.8.0"
gdk = "0.11.0"
gdk-pixbuf = "0.7.0"
vgtk-macros = { path = "../macros" }
proc-macro-hack = "0.5.10"
proc-macro-nested = "0.1.3"
log = "0.4.8"
colored = "1.8.0"

[dependencies.gtk]
version = "0.7.0"
features = ["futures", "embed-lgpl-docs", "v3_20"]
