[package]
name = "vgtk"
version = "0.1.0"
authors = ["Bodil Stokke <bodil@bodil.org>"]
edition = "2018"

[dependencies]
gio = "0.7.0"
glib-sys = "0.9.0"
gtk-sys = "0.9.0"
gobject-sys = "0.9.0"
glib = "0.8.0"
gdk-pixbuf = "0.7.0"
vgtk-macros = { path = "../macros" }
proc-macro-hack = "0.5.10"

[dependencies.gtk]
version = "0.7.0"
features = ["futures", "embed-lgpl-docs"]
