name: Continuous Integration
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 1,15 * *"

jobs:
  test:
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, beta, nightly]

    steps:
      - name: Update packages
        run: sudo apt-get update
      - name: Install Gtk build environment
        run: sudo apt-get install -y libgtk-3-dev
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@v1
      - name: Run tests in macros
        run: cd macros; cargo test --all-features
      - name: Run tests in lib
        run: cd vgtk; cargo test --all-features

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Update packages
        run: sudo apt-get update
      - name: Install Gtk build environment
        run: sudo apt-get install -y libgtk-3-dev
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
          components: clippy
      - uses: actions/checkout@v1
      - name: Clippy
        run: cargo clippy -- -D warnings
